### PR TITLE
Feature: Provide additional custom init script

### PR DESCRIPTION
**Pull request by mohanjith**
Provide script in the file system that should be run after first init

### CODE REVIEW

**Comment by eduble** [comment]
Hi,
Thanks. I have updated your proposal a little and merged it in `dev`.

* I moved the test about the existence of the script a little later (after the test for the existence of the chroot environment itself; otherwise in case the chroot env path is wrong, the error message the user gets is about this script file) and tested for execute permission (instead of read permission)
* I changed the description in the man page to indicate that it can work with other kinds of executables too (not just scripts) and to mention how the path should be specified (i.e. relative to the root of the chroot env)
* I mentioned this new option and your name in debian/changelog

Thanks again for contributing!
Etienne

**Comment by mohanjith** [comment]
Do you think you could release this to the PPA soon?

**Comment by eduble** [comment]
Well it would not make a featureful 2.7 release, but if you need it, yes.
Did you imagine other features that could be useful?

**Comment by mohanjith** [comment]
2.6.1 maybe :) 

I don't have any other features in mind.

**Comment by eduble** [comment]
Version 2.7 is now available on PPA.

**Comment by mohanjith** [comment]
Thank you very much!

**Pull request closed without merging**
